version: '3.9'

services:
  # See: https://hub.docker.com/_/postgres
  postgres-database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  ledger-api:
    image: digitalasset-docker.jfrog.io/daml-on-sql:${DAML_SDK_VERSION}
    depends_on:
      - postgres-database
    command: >
      --address=0.0.0.0
      --port=${LEDGER_PORT}
      --ledgerid=${LEDGER_ID}
      --sql-backend-jdbcurl=${JDBC_URL}
    ports:
      - ${LEDGER_PORT}:${LEDGER_PORT}
  json-api:
    image: digitalasset-docker.jfrog.io/http-json:${DAML_SDK_VERSION}
    restart: on-failure
    depends_on:
      - ledger-api
    command: >
      --address=0.0.0.0
      --ledger-host=ledger-api
      --ledger-port=${LEDGER_PORT}
      --http-port=${HTTP_PORT}
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
